version: 0.2

phases:
  
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Start build"
    
  build:
    commands:
      - echo "Building..."
      
  post_build:
    commands:
      - echo Build completed on `date`
      

 